### ISSUE TITLE
To do?

### ISSUE THREAD

**Issue by Ronan-Farrell** [Bugscz/GeoView#1]
Hello,

I don't suppose you got around to completing this?

Regards,
Ronan

**Comment by Bugscz** [comment]
Hi,

you are right. I discarded this project for lack of documentation and no luck with reverse-engineering advanced .geo files. I had implemented rendering of some basic objects as lines, circles, arc. But decided to not release that to public because of zero functionality. I am sorry. Maybe in future I'll take a look at it.
